export const FETCH_LOCATIONS_PENDING = 'FETCH_LOCATIONS_PENDING';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';

export const FETCH_LOCATION_PRODUCTS_PENDING = 'FETCH_LOCATION_PRODUCTS_PENDING';
export const FETCH_LOCATION_PRODUCTS_SUCCESS = 'FETCH_LOCATION_PRODUCTS_SUCCESS';
export const FETCH_LOCATION_PRODUCTS_FAILURE = 'FETCH_LOCATION_PRODUCTS_FAILURE';

export const FETCH_PRODUCT_PENDING = 'FETCH_PRODUCT_PENDING';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

export const CHANGE_LOCATION_SCANNER_STATE = 'CHANGE_LOCATION_SCANNER_STATE';

export const CHANGE_NETWORK_STATUS = 'CHANGE_NETWORK_STATUS';

export const OFFLINE_PRODUCT_LIST_RETRIEVED = 'OFFLINE_PRODUCT_LIST_RETRIEVED';

export const APP_REHYDRATED = 'APP_REHYDRATED';

export const UPDATE_PRODUCT_FORM = 'UPDATE_PRODUCT_FORM';
export const CLEAR_PRODUCT_FORM = 'CLEAR_PRODUCT_FORM';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
